### ISSUE TITLE
How to build .bat files while packaging on linux

### ISSUE THREAD

**Issue by apric0ts** [NVIDIA-Omniverse/kit-app-template#12]
I have a linux x86-64 machine and want to thin package my app and generate `pull-kit-sdk` and other files for BOTH linux and windows for cross-platform development.

When I package my kit app using the template in thin format following commands from the [kit-app-template docs](https://docs.omniverse.nvidia.com/kit/docs/kit-app-template/latest/docs/packaging_app.html#thin-package), only `.sh` files are generated, and Windows cant run those files. How can I generate `.bat` files using the template on linux? 

From this repo's readme:
> The kit-app-template enables developers to create cross-platform (Windows and Linux) accelerated applications

Here's a screenshot of the files generated from thin package:
![image](https://github.com/NVIDIA-Omniverse/kit-app-template/assets/69058754/1e335f47-0172-4f54-8b0d-8c9f043df94a)

**Comment by SchultzC** [comment]
The tooling and templates will work cross platform. However, the packaging operation will generate the required package for the OS you are currently using.  Packaging your application on Windows will generate the required .bat files
