### ISSUE TITLE
Is this out of BETA?

### ISSUE THREAD

**Issue by cadop** [NVIDIA-Omniverse/kit-app-template#17]
The readme states it is for 106 beta, the release notes for 106.1 Release has a hyperlink to this being the kit app template.

**Comment by SchultzC** [comment]
As of Kit 106.0.1 (and our latest update to Kit 106.0.2), Kit 106 is out of BETA.

Please note that this repository will continue to receive patch updates for Kit SDK 106.0.x as they become available.

Going forward, the Kit App Template repository will be branched by the minor (or major) version of Kit SDK. Currently, the main branch is on Kit 106.0.x. When 106.1.0 becomes available, a 106.0 branch will be created, and the main branch will move to 106.1.x
