### ISSUE TITLE
Deploying the  app  template to OV Launcher

### ISSUE THREAD

**Issue by BrunoItaly** [NVIDIA-Omniverse/kit-app-template#18]
Hello,
following these  instructions I was able to build and run an app starting from the templates  but didn't find any notes about publishing the app into OV Launcher,  both Workstation or Enterprise.

I tried to deploy a packaged app using  a command like   "start omniverse-launcher://install?path="<package.zip>"

but it fails as, I understood,  the package is missing a description.toml  file.

The part of installing on Launcher  is missing from all the documentations.  
I'm trying to build the description.toml file  myself but  it's hard and some hint or tool will help to shorten the process.

**Comment by BrunoItaly** [comment]
I just found some instructions here,  maybe this is useful to somebody else

https://docs.omniverse.nvidia.com/kit/docs/kit-app-template/105.1/packaging_app.html

**Comment by SchultzC** [comment]
This is the latest available instructions on adding to Launcher.  Thank you for adding a resolution.
