### ISSUE TITLE
[BUG]: Kit app will not build if drive is not formatted with NTFS

### ISSUE THREAD

**Issue by apric0ts** [NVIDIA-Omniverse/kit-app-template#20]
### Description

On Windows, using a drive formatted with exFAT, an error is given when running the repo build command.

`packman.errors.PackmanError: Failed to create junction at 'E:\apric\repos\my-app\_repo\deps\repo_man' (Local NTFS volumes are required to complete the operation.`

### Component

repo build tool

### System Details

Windows OS, exFAT 

### Reproduction Steps

Confirm that drive is not formatted with NTFS.
Run ./repo.bat build command

### Logs

It doesn't get to either of these points, at this stage the `_repo/repo.log` file is not generated, and the `_build` folder is not generated either.

**Comment by SchultzC** [comment]
Our dependency fetching and caching layer requires a filesystem that supports Windows junctions/soft links (symlinks) to enable linking dependencies from the cache. This ensures we can maximize the reuse of common components and libraries. Unfortunately, exFAT does not support this.

In the near term we will add this information to our documentation for future reference.

**Before we close this issue, could you please share more about your use case?** 
We want to ensure we aren't missing any important scenarios that we should consider supporting.

**Comment by apric0ts** [comment]
I had wanted to run Omniverse from a flash drive, it just so happened to be formatted with exFAT, and I had just changed it to NTFS and it works fine. It's not much of an issue, feel free to close this.

**Comment by SchultzC** [comment]
Thanks for the update.  

To ensure we address similar issues we have added a section on this topic to the [Usage and Trouble Shooting documentation](https://github.com/NVIDIA-Omniverse/kit-app-template/blob/main/readme-assets/additional-docs/usage_and_troubleshooting.md#exfat-drive-compatibility-limitations)
