### ISSUE TITLE
[BUG]: Could not find cgroup memory limit 

### ISSUE THREAD

**Issue by irepela** [NVIDIA-Omniverse/kit-app-template#21]
### Description

An error occurs during .\repo.bat build:

<img width="350" alt="image" src="https://github.com/user-attachments/assets/2672e840-f4ce-4ee8-a985-20c2de37604c">

### System Details

Windows/RTX4090

### Reproduction Steps

1. Create a new Application using  .\repo.bat template new
2. Build an app using .\repo.bat build

**Comment by SchultzC** [comment]
Thank you for reporting.

This should not be a blocking issue as the build should still complete successfully. 

If you find that the build does not complete successfully please let us know.

We have addressed this in an upcoming release.  We will leave this issue open until that fix has been added.

**Comment by irepela** [comment]
Thanks. It does not block the build.

**Comment by abhilashca** [comment]
Me too have this issue but is not blocking the build.

**Comment by Yiju1213** [comment]
same this issue, also not blocking the build.

**Comment by SchultzC** [comment]
This bug has been addressed starting with Kit 106.1.0 (currently on main)
