### ISSUE TITLE
[QUESTION]: Clarify role of extensions in omniverse

### ISSUE THREAD

**Issue by cadop** [NVIDIA-Omniverse/kit-app-template#24]
### Question

To start, I understand KIT is focused on a lightweight SDK for a gui wrapper with a renderer for USD files, and physics with those USDs.  As recent as last week, nvidia was explaining omniverse as a platform as a bunch of extensions, not a software. The new template docs do greatly help this clarification. 

However, there was a recent discussion on the community regarding extensions, which said: 

*Question*: 

> How to make custom support level type categories on the extensions manager?  It seems only Core works, and everything else gets put into Sample

*Answer*:
> I don’t think we have designed it that way. The extension manager is there for you to add extensions to your project. Not re-organize it
> And it is designed to be for “your eyes only” meaning only you the developer ever sees it. Then you remove it by taking away the developer bundle and ship the app. You are not allowed to ship the developer bundle anyway.

If there is a way, please let me know, otherwise the following is confusing regarding the statement:

--------

Looking at the docs: 
https://docs.omniverse.nvidia.com/kit/docs/kit-app-template/latest/docs/kit_sdk_overview.html# states: `At its core, the Omniverse Kit SDK is a framework for efficiently managing extensions and plugins.`

![image](https://github.com/user-attachments/assets/4ada92bb-dd4c-494e-bc05-9f1b3087a2e3)

The image shows an "Ext Manager".  A key feature is listed as `Extension System: Manages the extension lifecycle process.`

Building with kit says `At the heart of this development process are the concepts of extensions and applications.`

There is a section of the overview called 'Extensions", and the emphasis is in fact on **everything is an extension**, pointing out it is "highly modular".

> The Kit platform is highly modular; **everything is an extension**. Extensions are uniquely named and versioned packages, loaded at runtime, and can include Python code, shared libraries, along with C++ or Python APIs, and more. Extensions can be developed independently and can depend on other extensions, offering a high degree of flexibility.

This says `loaded at runtime`. 

> Developers can develop their own extensions or leverage extensions provided by NVIDIA via the Kit SDK or an NVIDIA managed extension registry.

` leverage extensions provided by ... NVIDIA managed extension registry.`

Summary
----------

So to begin, the documentation for [thin packages ](https://docs.omniverse.nvidia.com/kit/docs/kit-app-template/latest/docs/packaging_app.html#thin-package) says: `Thin packages contain the bare minimum required for an installation to be possible`.  If we need to remove the build tools before releasing, we can't use the thin package manager because it requires the ability to download Kit Kernel and extensions when the app is installed.

The package requires to `Run the pull_kit_sdk script to download the Kit Kernel and extensions`. This is, going back to the explanation of kit, using the `NVIDIA managed extension registry`, of which `omni.kit.window.extensions` is part of.  So there is an undisclosed set of extensions within the registry that are not allowed to be included?

Runtime
--------

The phrasing is confusing here. Multiple references are made to a highly modular system and **loaded at runtime**.  What is the value of this? 

A `.dll` is also loaded at runtime, it's just how code works. Therefore, I would assume this is something more meaningful, such as referencing the ability to hot-reload and _enable_ code after application has startup.  

However, if extensions are not meant to be loaded while using the application, and instead are predetermined in a kit file, which also includes the dependencies, and are downloaded into the users folder on first install... again what is the point of it being runtime?

Framing
--------

It would help if the docs could be modified to match the intentions for KIT.  Assuming the original premise is true (otherwise this is a long text for no reason), it seems like "toning down" the language would help alot. It seems to be phrased in a way to overpromise-underdeliver.  

Taken at face-value, the language of being _highly modular, loaded at runtime, has an extension manager with dependencies_... is just saying "**You can use Python**".

Use-case challenges
--------------------

This discussion was not a thought experiment, it has practical issues for us right now. 

If I am making extensions with the kit sdk (and to be clear, based on the nvidia docs, `making extensions = create an app`), and want users to not need to download unnecessary ones... isn't that what the extensions window is for? 

- Why would extensions even be a thing if the end result is that everything is part of an app build?

- How do I push updates to my users on a specific extension? Isn't that what the extensions window has been used for?

- How can my app allow users to take advantage of extensions made by 3rd parties? Say i made a digital twin simulator, and someone posts on github a plugin for my app? This is something Autodesk, ADOBE, All web browsers, essentially every software with an SDK I can think of has a way to integrate 3rd party extensions without needing to reinstall the entire application. 

- Similar point, I want to offer users a way to interface with my application.  There is no extension manager, so they can't write an extension to be loaded?

My Guess
----------

I can only guess here, but in the end, if the extension window is part of core kit, pretty much the entire discussion is mute.  Maybe its to avoid people installing nvidia extensions? That doesn't make sense to me since they can be included from the start, but sure.  Just making an extension window usable in applications would let people write plugins for software, and with that in mind, should be organizable from the app developer to have custom categories-- e.g. Rendering (materials, IES files), Generative Design (shape optimization), that could be access controlled via some token. 

If you got this far, thank you.

**Comment by apric0ts** [comment]
Many great points were made here regarding the Extensions window, specifically the use of the extensions window for *users* and not just developers. I would love to hear more about the answers to the questions under the `Use-case challenges` section.

**Comment by SchultzC** [comment]
Thank you for your detailed question and for taking the time to format it so thoroughly—it makes it much easier to parse.

Firstly, let's clarify the distinction between the Extension Manager Window UI Extension and the core Extension Management features of Kit:

1. **Extension Manager Window UI Extension**: This is a developer tool designed to help you browse and manage NVIDIA-provided extensions during development. It is not meant to be exposed to end-users in a final application release.

2. **Extension Management (Core Kit Feature)**: This refers to the underlying system within Kit that manages the lifecycle of extensions—such as loading, unloading, and updating extensions. This is a critical feature that ensures extensions behave correctly within your application.


The Kit SDK does support dynamic enabling and disabling of extensions outside the Extensions Manager Window UI. Here's a quick example of how you could enable an extension programmatically:

```python
import omni.kit.app

ext_manager = omni.kit.app.get_app().get_extension_manager()

ext_name = "your.kit.extension"

# Enable immediately
ext_manager.set_extension_enabled_immediate(ext_name, True)

# Or enable on the next update
ext_manager.set_extension_enabled(ext_name, True)
```

As far as being able to update or download extensions when you need them, this is something that is made possible by [Omniverse Client Library](https://docs.omniverse.nvidia.com/kit/docs/client_library/latest/docs/python.html)

The questions you raise highlight an opportunity for clarity within our documentation and we will work to clarify the language used going forward. 

If you have any specific workflows or scenarios you would like better supported or documented, please consider creating a feature request

**Comment by SchultzC** [comment]
Let us know if you need any more clarification. If not, we'll go ahead and close this question.

If you have any requests for additional documentation or tutorials to support what you're trying to create, feel free to submit them as a feature request.
