### ISSUE TITLE
[QUESTION]: There is no VR functionality in the Kit 106 USD Composer

### ISSUE THREAD

**Issue by kokashking** [NVIDIA-Omniverse/kit-app-template#25]
### Question

In the Kit 105 the VR Functionality was a standard feature. To our regret if we build the Kit 106 USD Composer template from the GitHub Repo there is no VR functionality. Are there any updates on the topic?

Thx in advance

**Comment by SchultzC** [comment]
You are correct that the USD Composer developer template has been refined to focus on its core features, based on typical Omniverse workflows such as generating assets for product configurators.

However, as a developer template, it is meant to be extended. There are a number of extensions not included in the Composer developer template by default that you might want to explore and potentially add as dependencies to your application’s `.kit` file.

To view these, launch your application with the Developer Bundle enabled:

**Linux**
```sh
./repo.sh launch -d
```

**Windows**
```bat
.\repo.bat launch -d
```

Navigate to `Developer > Extensions` and search for the extension you would like to add.

If you find that you are still unable to locate the extension you need for your workflow, please consider filing a feature request.
