### ISSUE TITLE
[QUESTION]: auto_load_usd option is giving error on windows

### ISSUE THREAD

**Issue by 3desinc** [NVIDIA-Omniverse/kit-app-template#26]
### Question
USDViewer Application

When running the following command (.\repo.bat launch -- --/app/auto_load_usd=D:/stage01.usd)  in Windows, I get error. Tried different options including enclosing with "" and ' '. The app opens but get file loading error.

nandu

### Additional Context

[113.638s] app ready
2024-09-23 12:04:42 [130,810ms] [Error] [omni.usd] Failed to open : D:/stage01.usd

Attaching the log
[kit_20240923_080231.log](https://github.com/user-attachments/files/17097222/kit_20240923_080231.log)

**Comment by SchultzC** [comment]
There are a couple of things to check here:

1) It looks like you are passing `D:/stage01.usd` as the full path to the sample asset.  Unless you have moved the asset out of the Viewer setup extension this doesn't appear to be the correct path.  By default the correct path will have the following form : 

```bash
{replace-with-full-path-to-kit-app-template}\source\extensions\{replace-with-setup-extension-name}\samples\stage01.usd
```

2) If you have intentionally moved the sample asset to `D:/stage01.usd` it's worth checking if you have `git-lfs` configured correctly to ensure the asset has been successfully pulled down from github.

**Comment by Administrators-0001** [comment]
Actually, I am facing a problem with my device and now I am reinstalling Windows, but if there is something wrong on my part, I will be happy to delete or modify it. Please guide me.

احصل على Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 3desinc** [comment]
Thanks Chris Schultz. It works when I do the git pull of the kit-app-template folder (instead of downloading a zip folder and unzipping it) and also point the stage01.usd in the source/examples folder as you mentioned. Thanks, Nandu

**Comment by SchultzC** [comment]
Perfect.  With that I'll close out this question.
