### ISSUE TITLE
FIleNotFoundError: all-deps.packman.xml invoking build.bat

### ISSUE THREAD

**Issue by h1r0ok** [NVIDIA-Omniverse/kit-app-template#3]
I've got FIleNotFoundError: all-deps.packman.xml when I invoked build.bat. log is here.

C:\Users\MyUserName\Downloads\kit-app-template-main\kit-app-template-main>build.bat
>>> Fetching all dependencies.
>>> Before Pull Commands Step. Running 'C:/Users/MyUserName/Downloads/kit-app-template-main/kit-app-template-main/repo.bat link_app'...

Found following Omniverse Apps:
0: cache-2022.2.0 (name: Cache, path: C:\Users\MyUserName\AppData\Local\ov\pkg\cache-2022.2.0)
1: kit-103.5.1 (name: Kit, path: C:\Users\MyUserName\AppData\Local\ov\pkg\kit-103.5.1)
2: view-2022.2.1 (name: View, path: C:\Users\MyUserName\AppData\Local\ov\pkg\view-2022.2.1)
3: nucleus-workstation-2022.3.0 (name: Nucleus Workstation, path: C:\Users\MyUserName\AppData\Local\ov\pkg\nucleus-workstation-2022.3.0)
4: navigator-3.2.0 (name: Nucleus Navigator, path: C:\Users\MyUserName\AppData\Local\ov\pkg\navigator-3.2.0)
5: drive-100.1.11 (name: Drive, path: C:\Users\MyUserName\AppData\Local\ov\pkg\drive-100.1.11)
6: xr-2022.2.0-rel.1 (name: Create XR, path: C:\Users\MyUserName\AppData\Local\ov\pkg\xr-2022.2.0-rel.1)
7: usdview-0.22.8 (name: USDView, path: C:\Users\MyUserName\AppData\Local\ov\pkg\usdview-0.22.8)
8: connectsample-200.1.0 (name: Connect Sample, path: )
9: code-2022.2.0 (name: Code, path: C:\Users\MyUserName\AppData\Local\ov\pkg\code-2022.2.0)
10: create-2022.2.2 (name: Create, path: C:\Users\MyUserName\AppData\Local\ov\pkg\create-2022.2.2)
11: mineways-10.1.0 (name: Mineways, path: C:\Users\MyUserName\AppData\Local\ov\pkg\mineways-10.1.0)
12: marbles_rtx-2021.1.5 (name: Marbles RTX, path: C:\Users\MyUserName\AppData\Local\ov\pkg\marbles_rtx-2021.1.5)
13: showroom-2022.1.0 (name: Showroom, path: C:\Users\MyUserName\AppData\Local\ov\pkg\showroom-2022.1.0)

Selected app: create-2022.2.2 (name: Create, path: C:\Users\MyUserName\AppData\Local\ov\pkg\create-2022.2.2)
Creating a link 'C:/Users/MyUserName/Downloads/kit-app-template-main/kit-app-template-main/_build/windows-x86_64/release/baseapp' -> 'C:\Users\MyUserName\AppData\Local\ov\pkg\create-2022.2.2'
Creating a link 'C:\Users\MyUserName\Downloads\kit-app-template-main\kit-app-template-main\_build\windows-x86_64\release\kit' -> 'C:\Users\MyUserName\AppData\Local\ov\pkg\create-2022.2.2/kit'
Successfully linked an app: create-2022.2.2 (name: Create, path: C:\Users\MyUserName\AppData\Local\ov\pkg\create-2022.2.2)!
[2022-11-16 17:57:38,402][ERROR][omni.repo.man.entry] Exception encountered while running repo_build via ['C:\\Users\\MyUserName\\Downloads\\kit-app-template-main\\kit-app-template-main\\tools\\repoman\\repoman.py', 'build']:
Traceback (most recent call last):
  File "C:\Users\MyUserName\Downloads\kit-app-template-main\kit-app-template-main\_repo\deps\repo_man\omni\repo\man\entry.py", line 350, in run_tool
    options.func(options)
  File "C:\Users\MyUserName\Downloads\kit-app-template-main\kit-app-template-main\_repo\deps\repo_man\omni\repo\man\entry.py", line 201, in <lambda>
    func=lambda args, func=func, config=merged_tool_config: func(args, config),
  File "C:\Users\MyUserName\Downloads\kit-app-template-main\kit-app-template-main\_repo\deps\repo_build\omni\repo\build\main.py", line 967, in run_repo_tool
    run_build(options, repo_folders, None, config)
  File "C:\Users\MyUserName\Downloads\kit-app-template-main\kit-app-template-main\_repo\deps\repo_build\omni\repo\build\main.py", line 699, in run_build
    repo_folders=repo_folders, platform_host=platform_host, platform_target=platform_target, configs=configs
  File "C:\Users\MyUserName\Downloads\kit-app-template-main\kit-app-template-main\_repo\deps\repo_man\omni\repo\man\nvteamcity.py", line 190, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\MyUserName\Downloads\kit-app-template-main\kit-app-template-main\_repo\deps\repo_build\omni\repo\build\main.py", line 335, in pull_dependencies
    pull_files(packman_target_files_to_pull, platform_target, dependencies)
  File "C:\Users\MyUserName\Downloads\kit-app-template-main\kit-app-template-main\_repo\deps\repo_build\omni\repo\build\main.py", line 320, in pull_files
    return_extra_info=True,
  File "C:\packman-repo\packman-common\6.42\packman\utils.py", line 506, in wrapper_message_block
    return func(*args, **kwargs)
  File "C:\packman-repo\packman-common\6.42\packman\main.py", line 1175, in pull
    project_path, platform, postscript, remotes, include_tags, exclude_tags, tokens
  File "C:\packman-repo\packman-common\6.42\packman\main.py", line 1194, in pull_with_variable_file
    project = parse_project_file(project_file_path, tokens, platform)
  File "C:\packman-repo\packman-common\6.42\packman\main.py", line 976, in parse_project_file
    return proj_parser.parse_file(project_file_path, tokens_n_platform)
  File "C:\packman-repo\packman-common\6.42\packman\schemaparser.py", line 1170, in parse_file
    return super(ProjectParser, self).parse_file(path, ".user", tokens)
  File "C:\packman-repo\packman-common\6.42\packman\xmlparser.py", line 235, in parse_file
    root = self._parse_file(filename, tokens)
  File "C:\packman-repo\packman-common\6.42\packman\xmlparser.py", line 275, in _parse_file
    p.ParseFile(fileobject)
  File "..\Modules\pyexpat.c", line 417, in StartElement
  File "C:\packman-repo\packman-common\6.42\packman\xmlparser.py", line 196, in start_element
    element.start_handler(self, attributes)
  File "C:\packman-repo\packman-common\6.42\packman\schemaparser.py", line 842, in start_handler
    project = ProjectParser().parse_file(path_abs, parse_helper.tokens)
  File "C:\packman-repo\packman-common\6.42\packman\schemaparser.py", line 1170, in parse_file
    return super(ProjectParser, self).parse_file(path, ".user", tokens)
  File "C:\packman-repo\packman-common\6.42\packman\xmlparser.py", line 235, in parse_file
    root = self._parse_file(filename, tokens)
  File "C:\packman-repo\packman-common\6.42\packman\xmlparser.py", line 272, in _parse_file
    with open(path, "rb") as fileobject:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\MyUserName\\Downloads\\kit-app-template-main\\kit-app-template-main\\_build\\windows-x86_64\\release\\kit\\dev\\all-deps.packman.xml'

**Comment by joreeves** [comment]
Have the same issue. @h1r0ok Did you find a solution?

**Comment by h1r0ok** [comment]
Today, I tried with newly installed PC and Create-2022.3.1, then it have been SUCCEEDED.
I don't know what was wrong, but anyway, I am going to close this issue...




C:\Users\MyUserName\Documents\git\kit-app-template>build.bat
>>> Fetching all dependencies.
>>> Before Pull Commands Step. Running 'C:/Users/MyUserName/Documents/git/kit-app-template/repo.bat link_app'...

Found following Omniverse Apps:
0: cache-2022.2.0 (name: Cache, path: C:\Users\MyUserName\AppData\Local\ov\pkg\cache-2022.2.0)
1: nucleus-workstation-2022.4.1 (name: Nucleus Workstation, path: C:\Users\MyUserName\AppData\Local\ov\pkg\nucleus-workstation-2022.4.1)
2: create-2022.3.1 (name: Create, path: C:\Users\MyUserName\AppData\Local\ov\pkg\create-2022.3.1)
3: view-2022.3.3 (name: View, path: C:\Users\MyUserName\AppData\Local\ov\pkg\view-2022.3.3)
4: code-2022.3.1 (name: Code, path: C:\Users\MyUserName\AppData\Local\ov\pkg\code-2022.3.1)
5: drive-100.1.7 (name: Drive, path: C:\Users\MyUserName\AppData\Local\ov\pkg\drive-100.1.7)
6: kit-104.1.0 (name: Kit, path: C:\Users\MyUserName\AppData\Local\ov\pkg\kit-104.1.0)
7: usdview-0.22.11 (name: USDView, path: C:\Users\MyUserName\AppData\Local\ov\pkg\usdview-0.22.11)

Selected app: create-2022.3.1 (name: Create, path: C:\Users\MyUserName\AppData\Local\ov\pkg\create-2022.3.1)
Creating a link 'C:/Users/MyUserName/Documents/git/kit-app-template/_build/windows-x86_64/release/baseapp' -> 'C:\Users\MyUserName\AppData\Local\ov\pkg\create-2022.3.1'
Creating a link 'C:\Users\MyUserName\Documents\git\kit-app-template\_build\windows-x86_64\release\kit' -> 'C:\Users\MyUserName\AppData\Local\ov\pkg\create-2022.3.1/kit'
Successfully linked an app: create-2022.3.1 (name: Create, path: C:\Users\MyUserName\AppData\Local\ov\pkg\create-2022.3.1)!
Package 'premake' at version '5.0.0-alpha15.dev+pipeline3388156.1f299ea4-windows-x86_64' is missing from local storage.
Downloading from https://d4i3qtqj3r0z5.cloudfront.net/premake%405.0.0-alpha15.dev%2Bpipeline3388156.1f299ea4-windows-x86_64.7z (429 KiB)
100.00% (speed 726 KiB/s)
Total of 0.59 seconds
Extracting: premake@5.0.0-alpha15.dev+pipeline3388156.1f299ea4-windows-x86_64.7z (429 KiB)

100% (speed 52.4 MiB/s)
Total of 0.03 seconds
Output size: 1.34 MiB
Package successfully installed to C:\packman-repo\chk\premake\5.0.0-alpha15.dev+pipeline3388156.1f299ea4-windows-x86_64
Package 'msvc' at version '2019-16.7.6-license' is missing from local storage.
Downloading from https://d4i3qtqj3r0z5.cloudfront.net/msvc%402019-16.7.6-license.7z (64.6 MiB)
100.00% (speed 16.0 MiB/s)
Total of 4.02 seconds
Extracting: msvc@2019-16.7.6-license.7z (64.6 MiB)


... ... ... ...


100% (speed 91.3 MiB/s)
Total of 3.14 seconds
Output size: 287 MiB
Package successfully installed to C:\packman-repo\chk\git\2.28.0-windows-x86_64
Build number: '104.0+main.0.134d2033.local'
Written to file: 'c:\Users\MyUserName\Documents\git\kit-app-template\_build\windows-x86_64\debug\VERSION'
Build number: '104.0+main.0.134d2033.local'
Written to file: 'c:\Users\MyUserName\Documents\git\kit-app-template\_build\windows-x86_64\release\VERSION'
Building configurations...
    Baking my_name.my_app...
    Baking my_name.my_app.viewport...
    Baking my_name.my_app.editor...
Running action 'vs2019'...
Generated _compiler/vs2019/kit-app-template.sln...
Generated _compiler/vs2019/my_name.my_app/my_name.my_app.vcxproj...
Generated _compiler/vs2019/my_name.my_app/my_name.my_app.vcxproj.user...
Generated _compiler/vs2019/my_name.my_app/my_name.my_app.vcxproj.filters...
Generated _compiler/vs2019/my_name.my_app.viewport/my_name.my_app.viewport.vcxproj...
Generated _compiler/vs2019/my_name.my_app.viewport/my_name.my_app.viewport.vcxproj.user...
Generated _compiler/vs2019/my_name.my_app.viewport/my_name.my_app.viewport.vcxproj.filters...
Generated _compiler/vs2019/my_name.my_app.editor/my_name.my_app.editor.vcxproj...
Generated _compiler/vs2019/my_name.my_app.editor/my_name.my_app.editor.vcxproj.user...
Generated _compiler/vs2019/my_name.my_app.editor/my_name.my_app.editor.vcxproj.filters...
Generated _build/windows-x86_64/debug/compile_commands.json...
Generated _build/windows-x86_64/release/compile_commands.json...
Done (8941ms).
>>> Stage Files Step. doing file copy and folder linking.
>>> File doesn't exist: C:/Users/MyUserName/Documents/git/kit-app-template/prebuild.toml. Skipping.
>>> Processing file: C:/Users/MyUserName/Documents/git/kit-app-template/_build/generated/prebuild.toml
>>> VS Code setup. Writing: C:\Users\MyUserName\Documents\git\kit-app-template\_build\windows-x86_64\release\setup_python_env.bat
>>> VS Code setup. Writing: C:\Users\MyUserName\Documents\git\kit-app-template\_build\windows-x86_64\release\site\sitecustomize.py
>>> VS Code setup. Writing: C:/Users/MyUserName/Documents/git/kit-app-template/.vscode/settings.json
Building using this MSBuild: C:/Users/MyUserName/Documents/git/kit-app-template/_build/host-deps\msvc\MSBuild\Current\Bin\MSBuild.exe
*** Building release ***
.NET Framework 向け Microsoft (R) Build Engine バージョン 16.7.0+b89cb5fde
Copyright (C) Microsoft Corporation.All rights reserved.

BUILD SUCCEEDED (Took 53.89 seconds)
