### ISSUE TITLE
[QUESTION]: Where and how can I increase the font size?

### ISSUE THREAD

**Issue by DataJuggler** [NVIDIA-Omniverse/kit-app-template#30]
### Question

Now that I have the code for Omniverse and am running my own version, can someone guide me on the places to look for font size so I can increase the menu fonts to something I can read please?

Thanks
![image](https://github.com/user-attachments/assets/301e304e-78dd-4028-8a95-82f6e15dd8aa)

**Comment by MikeWise1618** [comment]
Out of curiousity, which Menus? 

- The ones in these templates? (that depends on your OS temminal program)
- The ones in the compiled apps? (There are different sizes in the menu and in the various UI element menus? (not sure if you can override this but this would not be the place to ask - try the forums)
- The ones in your own UI elements? (you can control those with a "style" parameter when you create them)

My vision isn't great anymore, but I am not having much problems reading things - if I can find my glasses :).

**Comment by DataJuggler** [comment]
I may have solved it. In the source\apps folder, the .kit file for USD Composer has a few font settings. I changed the default size from 16 to 18 and rebuilt the app. I think the fonts are bigger now.

Here is the before 
![image](https://github.com/user-attachments/assets/1c60033e-1b8c-4406-adba-afd5e0da36d6)

Here is the after:
![image](https://github.com/user-attachments/assets/94fed037-56eb-47a4-82cf-01591c2338c3)

**Comment by SchultzC** [comment]
Thank you @DataJuggler for following up on your own question and posting your solution.  This is sincerely appreciated.

You are correct.  This can be set via the application `.kit` file.  The primary location is `settings.app.font.size`:

```toml
[settings.app.font]
file = "${fonts}/OpenSans-SemiBold.ttf"
size = 16
```

In some cases (like the Composer template) individual extensions have their own font settings as well, which correspond to the other locations you found.
