### ISSUE TITLE
[BUG]: tools/packman/python.sh: permission denied

### ISSUE THREAD

**Issue by onurbingol** [NVIDIA-Omniverse/kit-app-template#32]
### Description

`repo.sh build` fails due to a permission error on Ubuntu 22.04

### Component

repo build tool

### System Details

* Ubuntu 22.04.5 LTS
* Using`kit-app-template` repository `main` branch (Kit 106.2 EA)

### Reproduction Steps

* Clone this repository and checkout to `main` branch.
* Update `.toml` files as instructed and populate `source` directory (I have been using `kit-app-template` for a while, so I have existing apps and extensions)
* Run `./repo.sh build` on Ubuntu 22.04 LTS
* Get the following error

```
./repo.sh: line 13: /home/user/kit-app-template/tools/packman/python.sh: Permission denied
```

### Logs

No logs generated

### Additional Context

I believe you forgot to update the permissions of `python.sh` after you updated it. As you may already know, it is extremely simple to fix: `chmod +x tools/packman/python.sh`

**Comment by SchultzC** [comment]
Thank you for filing.  The simple fix you mention will work.  But we will also push a fix shortly and will close this issue at that time.

**Comment by SchultzC** [comment]
This issue has now been resolved.

**Comment by onurbingol** [comment]
@SchultzC  [this commit](https://github.com/NVIDIA-Omniverse/kit-app-template/commit/2a24524a9487f96622b49d91fb5355144f5da260) also removed the execute permissions of some other files as well, namely `tools/package.sh` and `tools/packman/packman`. I am not sure if they are used when `repo.sh` is called, but just in case, I wanted to let you know.
