### ISSUE TITLE
[BUG]: Launch.bat is missing from the latest release. Repo.bat doesn't launch the app.

### ISSUE THREAD

**Issue by DataJuggler** [NVIDIA-Omniverse/kit-app-template#38]
### Description

I looked at the repo and saw there was a new version, so I deleted the old directory and followed the instructions again.

This time, your instructions list launch as

.\repo.bat launch

I tried that, and the console window just closes, nothing happens. 

I still had Launch.bat in my recycle bin, so I restored that, and this launches the app.

Launch.bat -D

Not sure why you got rid of Launch.bat but it seems to be required.

### Component

USD Composer

### System Details

Windows 11, 19-12900K, RTX 3090, 128 Gig Memory

### Reproduction Steps

Follow your instructions and clone and build the app.

Repo.bat doesn't work, but the previous version had Launch.bat. 

Launch.bat works.

**Comment by DataJuggler** [comment]
This was my fault. I didn't have the launch parameter in my shortcut

Repo.bat launch.

**Comment by SchultzC** [comment]
Had us worried for a moment there.

**Comment by DataJuggler** [comment]
I did notice the -D doesn't work to turn on extensions, so I am using the old Launch.bat. Not sure why you changed to repo.bat.

**Comment by SchultzC** [comment]
That's correct.  `-D` won't work.  If you use:

**Linux:**
`./repo.sh launch -d`
or
`./repo.sh launch --dev-bundle`

**Windows**
`.\repo.bat launch -d`
or
`.\repo.bat launch --dev-bundle`

That should bring up Extension Manger within the Developer menu.
**Developer->Extensions**
