### ISSUE TITLE
USD Composer

### ISSUE THREAD

**Issue by VelazcoJD** [NVIDIA-Omniverse/kit-app-template#5]
Are there plans to update the repository to make it compatible with USD Composer (Create 2023.1.1)? I tried running it, but it seems there is an issue where custom extensions can't find Omniverse extensions. In other words, you can import an Omniverse extension in the app's .kit file, but the same extension fails to be imported in a custom extension's extension.toml file.

**Comment by VelazcoJD** [comment]
Also, it seems Omniverse Launcher update 1.8.11 broke the template as well.

![image](https://github.com/NVIDIA-Omniverse/kit-app-template/assets/15093269/b99226d7-62e3-4e6d-a2f7-1af1bf2b7337)
![image](https://github.com/NVIDIA-Omniverse/kit-app-template/assets/15093269/07315051-49bc-4ced-81b6-748b5b2cd20c)

**Comment by ronaldmaymone** [comment]
I'm facing the same issue. Maybe something to do with firewalls?

**Comment by VelazcoJD** [comment]
> I'm facing the same issue. Maybe something to do with firewalls?

I uninstalled v1.8.11 and installed an older version I had downloaded it and works just fine.

**Comment by ronaldmaymone** [comment]
> > I'm facing the same issue. Maybe something to do with firewalls?
> 
> I uninstalled v1.8.11 and installed an older version I had downloaded it and works just fine.

Thx!
For me the version Omniverse Launcher 1.8.2 worked

**Comment by MikeWise2718** [comment]
This issue title seems to be wrong, it is about the Launcher, not Composer. 

I had Lauchner v.1.8.11 and I had this issue. I didn't see an archive with old launchers in them so I went "dumpster diving" in my downloads and found an old v1.5. 7 from Aug 22 and that  fixed the problem after I installed it (it just overwrote 1.8.11, didn't have to uninstall it).

What do we learn from that? "Never empty out your downloads directory"

**Comment by ronaldmaymone** [comment]
So, apparently this repo is a old one. With the Kit 105 release the newest is 
https://github.com/NVIDIA-Omniverse/kit-project-template
That perfectly works with launcher 1.8.11 and the new USD Composer and Code.

**Comment by jaeyeun1** [comment]
> This issue title seems to be wrong, it is about the Launcher, not Composer.
> 
> I had Lauchner v.1.8.11 and I had this issue. I didn't see an archive with old launchers in them so I went "dumpster diving" in my downloads and found an old v1.5. 7 from Aug 22 and that fixed the problem after I installed it (it just overwrote 1.8.11, didn't have to uninstall it).
> 
> What do we learn from that? "Never empty out your downloads directory"

hello
Im experiencing a similar issue and I cannot switch to Kit 105 yet since I am trying to build and app with isaac sim extensions, which is based on kit 104.
can you be kind and share the installer for an older version of the Omniverse Launcher?
If you need my email let me know!
Thanks.

**Comment by jaeyeun1** [comment]
> hello
> Im experiencing a similar issue and I cannot switch to Kit 105 yet since I am trying to build and app with isaac sim extensions, which is based on kit 104.
> can you be kind and share the installer for an older version of the Omniverse Launcher?
> If you need my email let me know!
> Thanks.

hello
Im experiencing a similar issue and I cannot switch to Kit 105 yet since I am trying to build and app with isaac sim extensions, which is based on kit 104.
can you be kind and share the installer for an older version of the Omniverse Launcher?
If you need my email let me know!
Thanks.

**Comment by jaeyeun1** [comment]
> > > I'm facing the same issue. Maybe something to do with firewalls?
> > 
> > 
> > I uninstalled v1.8.11 and installed an older version I had downloaded it and works just fine.
> 
> Thx! For me the version Omniverse Launcher 1.8.2 worked

hello
Im experiencing a similar issue and I cannot switch to Kit 105 yet since I am trying to build and app with isaac sim extensions, which is based on kit 104.
can you be kind and share the installer for an older version of the Omniverse Launcher?
If you need my email let me know!
Thanks.

**Comment by polley** [comment]
Can someone here kindly point me to where I can find older versions of Launcher to install? Thanks!

**Comment by SchultzC** [comment]
As of the latest update.  A Composer like application experience can be created by building an app using the [USD Composer Template](https://github.com/NVIDIA-Omniverse/kit-app-template/tree/main/templates/apps/usd_composer).
