### ISSUE TITLE
Doc Broken Link

### ISSUE THREAD

**Issue by MikeWise2718** [NVIDIA-Omniverse/kit-app-template#6]
There is a link in the Kit App Template documentation that is supposed to point to this repo, but it is broken.

The relevent page: (https://docs.omniverse.nvidia.com/dev-guide/latest/kit-app-template.html)
 
The Kitt App Template link on that page points to:  (https://github.com/NVIDIA-Omniverse/kit-template) which is wrong.

It should be `kit-app-template`

**Comment by SchultzC** [comment]
Thank you.  This has been resolved.
