### ISSUE TITLE
Repo incompatible with Launcher 1.8.11

### ISSUE THREAD

**Issue by MikeWise2718** [NVIDIA-Omniverse/kit-app-template#7]
The build step in this repo seems to communicate with the launcher as the first step to upgrade all the repos. However with the current launcher (1.8.11) it fails, there is a screen shot of the error  in issue #4. I fixed it and got this repo to build only by downgrading the Launcher to an earlier version (1.5.7 in my case).

**Comment by polley** [comment]
Thanks for sharing the tip @MikeWise2718. How were you able to downgrade an already upgraded Launcher? Appreciate it!

**Comment by SchultzC** [comment]
The latest available instructions on building for Launcher is here:

https://docs.omniverse.nvidia.com/kit/docs/kit-app-template/105.1/packaging_app.html

go to the "Launcher Package" section close to the end of the page
