### ISSUE TITLE
<BUG> Build time Error Occur

### ISSUE THREAD

**Issue by XEL-Maker** [NVIDIA-Omniverse/kit-app-template#9]
We encountered a critical issue while building on the Windows system, 
stemming from the line provided below:

https://github.com/NVIDIA-Omniverse/kit-app-template/blob/a4f26f51f9e14bd3639e24a90a37b5dbe96e36b6/source/launcher/description.toml#L23

The command to reproduce this issue is as follows:

```
repo.bat package --launch
```

The reason for this critical issue is that the special character "tm" cannot be converted<br> from euc_kr (also known as cp949) to utf8.

If the inclusion of the word "tm" is not essential, please remove it.

**Comment by SchultzC** [comment]
Thank you for reporting.  cp949 has been removed from the 105.1 branch
